### ISSUE TITLE
Struggling to Get past Integration Screen

### ISSUE THREAD

**Issue by cloudbr34k84** [jcgoette/baby_buddy_homeassistant#103]
Unable to get the HA HACS integrating to work

Add On YAML Config
```
CSRF_TRUSTED_ORIGINS: https://ha.xxxxxxxxxx.xyz
NAP_START_MIN: "06:00"
NAP_START_MAX: "18:00"
USE_24_HOUR_TIME_FORMAT: true
INGRESS_USER: admin
log_level: info
```

When i go to add integration
I had the IP address of my HOME Assistant https://xxx.xxx.xx.xx
The port is unchanged
API key is copied from settings in Baby Buddy??

What am i missing??

**Comment by jcgoette** [comment]
Not sure. You haven't provided any error logs/messages. Looks like you are talking about the [addon](https://github.com/OttPeterR/addon-babybuddy) and this integration. I recommend reading through [this](https://github.com/jcgoette/baby_buddy_homeassistant/issues/89) for helpful hints.

**Comment by Marquo1** [comment]
I just installed the add-on and integration and also had some troubles to get it to work at first.
Integration setup would fail every time.

The problem was that the add-on did not open port 8000.
I had to manually set the web interface port to 8000 in Addon -> Configuration tab -> Network
That solved it.
