### ISSUE TITLE
Error: last_feeding sensor and add_feeding method are not working

### ISSUE THREAD

**Issue by MiguelCosta** [jcgoette/baby_buddy_homeassistant#74]
Hi,

I am trying to use this HA integration.

![image](https://user-images.githubusercontent.com/645482/186913589-94342e6b-d18e-443d-b9a6-721c6763e4d0.png)

But I think the feeding area is not working. 

`last_feeding` sensor is always `Unknown` and `add_feeding` method is not working too:

![image](https://user-images.githubusercontent.com/645482/186913833-0b371de5-7d77-4fd5-927c-8d27f284bfe0.png)

The error is:

```
Logger: homeassistant.helpers.service
Source: helpers/service.py:635
First occurred: 14:29:38 (2 occurrences)
Last logged: 14:29:49

Unable to find referenced entities sensor.baby_gaspar_costa or it is/they are currently not available
```

but the `add_diaper_change` is working:

![image](https://user-images.githubusercontent.com/645482/186915179-c4e91a23-9f6e-4847-98ea-eb6eecb10b5a.png)

Can you help? Why add_feeding method is failing but add_diaper_change is working?

- HA Version: 2022.8.7
- BabyBuddy Version: [v1.12.1](https://github.com/babybuddy/babybuddy/releases/tag/v1.12.1)
- BabyBuddy Home Assistant[v2.6.0](https://github.com/jcgoette/baby_buddy_homeassistant/releases/tag/v2.6.0)

**Comment by jcgoette** [comment]
`last_feeding` returns volume from last feed. If null, would be Unknown.

You should use the `switch.*_timer` entity as target. A quick search gives these as working examples:

- https://github.com/jcgoette/baby_buddy_homeassistant/issues/72#issuecomment-1164820403
- https://github.com/jcgoette/baby_buddy_homeassistant/issues/40#issuecomment-926980336
- https://github.com/jcgoette/baby_buddy_homeassistant/issues/41#issuecomment-939341144

**Comment by Emu05** [comment]
Maybe Explain this more clearly in the Main Instuctions took me half of a day to fugure it out untill i fount the closed section now .....

**Comment by jcgoette** [comment]
Which part?

Also, pull requests are welcome.

**Comment by Emu05** [comment]
> Which part?
> 
> Also, pull requests are welcome.

Maybe More Examples I tryed to implement the bottle scale Project and most of the code changed ( the automation Part) the add fedding changed at some point also maybe some basic Automation example code for the more complex things ( add feeding add tummy time and  sleep and maybe timer ) 

I its not my first implentation of addons also using HA for a long time now but this was hard to get it to this point i have now since there are not that many tutorials and projects around it and also not much sample code to figure it out. 

No critique its a nice addon othervices i would not have taken on time to get it working :) 
so it would be nice to have more example of code for eg and also code thats working with the latets releases of BB and HA
